### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by petrplasan** [UnAfraid/VotingReward#11]
Hi, Help me please :) i have this error: 

```log
[22:31:22] ERROR Failed to read user data
com.github.unafraid.votingreward.api.VotingRewardAPIException: Unable to execute getUserData method
	at com.github.unafraid.votingreward.api.VotingRewardAPIClient.sendApiMethod(VotingRewardAPIClient.java:126)
	at com.github.unafraid.votingreward.api.VotingRewardAPIClient.getUserData(VotingRewardAPIClient.java:59)
	at com.github.unafraid.votingreward.VotingRewardAPI.run(VotingRewardAPI.java:111)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.github.unafraid.votingreward.api.VotingRewardAPIException: Couldn't parse response content to json: null
	at com.github.unafraid.votingreward.api.VotingRewardAPIClient.sendApiMethod(VotingRewardAPIClient.java:117)
	... 9 more
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.l2topzone.com/v1/<EXCLUDED>/getUserData
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at com.github.unafraid.votingreward.api.VotingRewardAPIClient.sendApiMethod(VotingRewardAPIClient.java:112)
	... 9 more
````
token here was edited ...

**Comment by Julian367** [comment]
Contact website admin, you have 403 error (forbidden). "IOException: Server returned HTTP response code: 403 for URL: "

**Comment by UnAfraid** [comment]
Contact topzone administrator to whitelist your IP address, also i'd suggest to exclude your API key.
