### ISSUE TITLE
votingreward

### ISSUE THREAD

**Issue by VastoLordes** [UnAfraid/VotingReward#16]
[09:52:02] ERROR Failed to read user data
com.github.unafraid.votingreward.api.VotingRewardAPIException: Forbidden
        at com.github.unafraid.votingreward.api.TozoneVotingAPIClient.getResponse(TozoneVotingAPIClient.java:68)
        at com.github.unafraid.votingreward.api.TozoneVotingAPIClient.getTopzoneUserData(TozoneVotingAPIClient.java:60)
        at com.github.unafraid.votingreward.VotingRewardAPI.run(VotingRewardAPI.java:112)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by UnAfraid** [comment]
Contact topzone support, they need to whitelist your server IP address
